resources:
  - ../../base
  - namespace.yaml

namespace: oficina-ns

labels:
  - pairs:
      tags.datadoghq.com/env: "prod"
      tags.datadoghq.com/version: "1.0.0"
    includeSelectors: false
    includeTemplates: true

images:
  - name: pagamento-app
    newName: alexmarquesfa/pagamento-app # Adjust to your dockerhub user
    newTag: latest
