apiVersion: apps/v1
kind: Deployment
metadata:
  name: pagamento-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pagamento-app
  template:
    metadata:
      labels:
        app: pagamento-app
        admission.datadoghq.com/enabled: "true"
        tags.datadoghq.com/service: "pagamento"
        tags.datadoghq.com/env: "local"
        tags.datadoghq.com/version: "1.0.0"
    spec:
      containers:
      - name: pagamento-app
        image: pagamento-app
        ports:
        - containerPort: 8080
        env:
        - name: DD_SERVICE
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['tags.datadoghq.com/service']
        - name: DD_ENV
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['tags.datadoghq.com/env']
        - name: DD_VERSION
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['tags.datadoghq.com/version']
        - name: OTEL_SERVICE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['tags.datadoghq.com/service']
        - name: OTEL_ENVIRONMENT
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['tags.datadoghq.com/env']
        - name: OTEL_VERSION
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['tags.datadoghq.com/version']
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://$(DD_AGENT_HOST):4318"
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: PORT
          value: "8080"
        - name: MERCADO_PAGO_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: pagamento-secret
              key: mercadopago_access_token
        - name: MERCADO_PAGO_USER_ID
          valueFrom:
            configMapKeyRef:
              name: pagamento-config
              key: mercadopago_user_id
        - name: MERCADO_PAGO_POS_ID
          valueFrom:
            configMapKeyRef:
              name: pagamento-config
              key: mercadopago_pos_id
        - name: MERCADO_PAGO_WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: pagamento-secret
              key: mercadopago_webhook_secret
        - name: DYNAMODB_TABLE_NAME
          valueFrom:
            configMapKeyRef:
              name: pagamento-config
              key: dynamodb_table_name
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: pagamento-config
              key: aws_region
        - name: AWS_SNS_TOPIC_ARN
          valueFrom:
            configMapKeyRef:
              name: pagamento-config
              key: aws_sns_topic_arn
