apiVersion: v1
kind: Secret
metadata:
  name: pagamento-secret
type: Opaque
data:
  mercadopago_access_token: MERCADOPAGO_ACCESS_TOKEN_PLACEHOLDER
  mercadopago_webhook_secret: MERCADOPAGO_WEBHOOK_SECRET_PLACEHOLDER
