apiVersion: v1
kind: Secret
metadata:
  name: pagamento-secret
type: Opaque
stringData:
  mercadopago_access_token: MERCADOPAGO_ACCESS_TOKEN_PLACEHOLDER
  mercadopago_webhook_secret: MERCADOPAGO_WEBHOOK_SECRET_PLACEHOLDER
  aws_access_key_id: AWS_ACCESS_KEY_ID_PLACEHOLDER
  aws_secret_access_key: AWS_SECRET_ACCESS_KEY_PLACEHOLDER
  aws_session_token: AWS_SESSION_TOKEN_PLACEHOLDER
